config/routes.rb
Rails.application.routes.draw do
  root 'bootstraps#top'

  resources :bootstraps do
    collection do
      get :top
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bootstrap.rb
class Bootstrap < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bootstraps_controller.rb
class BootstrapsController < ApplicationController
  before_action :set_bootstrap, only: %i[ show edit update destroy ]

  # GET /bootstraps or /bootstraps.json
  def index
    @bootstraps = Bootstrap.all
  end

  # GET /bootstraps/1 or /bootstraps/1.json
  def show
  end

  # GET /bootstraps/new
  def new
    @bootstrap = Bootstrap.new
  end

  # GET /bootstraps/1/edit
  def edit
  end

  # POST /bootstraps or /bootstraps.json
  def create
    @bootstrap = Bootstrap.new(bootstrap_params)

    respond_to do |format|
      if @bootstrap.save
        format.html { redirect_to bootstrap_url(@bootstrap), notice: "Bootstrap was successfully created." }
        format.json { render :show, status: :created, location: @bootstrap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bootstrap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bootstraps/1 or /bootstraps/1.json
  def update
    respond_to do |format|
      if @bootstrap.update(bootstrap_params)
        format.html { redirect_to bootstrap_url(@bootstrap), notice: "Bootstrap was successfully updated." }
        format.json { render :show, status: :ok, location: @bootstrap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bootstrap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bootstraps/1 or /bootstraps/1.json
  def destroy
    @bootstrap.destroy

    respond_to do |format|
      format.html { redirect_to bootstraps_url, notice: "Bootstrap was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def top
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bootstrap
      @bootstrap = Bootstrap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bootstrap_params
      params.require(:bootstrap).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstraps_helper.rb
module BootstrapsHelper
end

app/views/bootstraps/_form.html.erb
<%= form_with(model: bootstrap, local: true) do |form| %>
  <% if bootstrap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bootstrap.errors.count, "error") %> prohibited this bootstrap from being saved:</h2>

      <ul>
        <% bootstrap.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bootstraps/edit.html.erb
<h1>Editing Bootstrap</h1>

<%= render 'form', bootstrap: @bootstrap %>

<%= link_to 'Show', @bootstrap %> |
<%= link_to 'Back', bootstraps_path %>

app/views/bootstraps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bootstraps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bootstraps.each do |bootstrap| %>
      <tr>
        <td><%= bootstrap.title %></td>
        <td><%= link_to 'Show', bootstrap %></td>
        <td><%= link_to 'Edit', edit_bootstrap_path(bootstrap) %></td>
        <td><%= link_to 'Destroy', bootstrap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bootstrap', new_bootstrap_path %>

app/views/bootstraps/new.html.erb
<h1>New Bootstrap</h1>

<%= render 'form', bootstrap: @bootstrap %>

<%= link_to 'Back', bootstraps_path %>

app/views/bootstraps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bootstrap.title %>
</p>

<%= link_to 'Edit', edit_bootstrap_path(@bootstrap) %> |
<%= link_to 'Back', bootstraps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapWorkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>